export const FILE_EXPLANATIONS = {
  wildcards: "Root scope domains you provided (e.g., example.com). Recon tools expand these into discovered subdomains.",
  domains: "All discovered domains/subdomains in scope before HTTP liveness filtering.",
  domains_http: "Live HTTP(S) domains that responded to probing; these are primary attack targets.",
  domains_dead: "Discovered domains that did not respond to HTTP probing (useful for passive review only).",
  apidomains: "Discovered API-like domains/endpoints (api.*, *-api, graphql/gateway-style hostnames).",
  apidomains_http: "Live API domains that responded to HTTP probing.",
  apidomains_dead: "API-like domains that did not respond to HTTP probing.",
  organizations: "Organization/company names used as seed input for dorking and discovery workflows.",
  ips: "IP addresses found during recon (for infrastructure profiling and segmentation checks).",
  out_of_scope: "Explicitly excluded targets; flow should avoid testing these hosts/domains.",
  robots_urls: "URLs extracted from robots.txt/sitemap paths; often reveals hidden or low-linked endpoints.",
  wayback_urls: "Historical URLs from web archives; useful for old endpoints and forgotten functionality.",
  katana_urls: "Crawler-discovered URLs from active crawling against live targets.",
  all_urls: "Merged URL corpus from multiple discovery sources; baseline input for later fuzzing stages.",
  params_candidates: "Likely parameter names collected for parameter fuzzing and replay-based behavior checks.",
  fuzzing_doc_hits: "Potential documentation endpoints found via ffuf (docs, swagger, openapi, api-reference paths).",
  fuzzing_dir_hits: "Potential interesting directories/API paths found via ffuf brute-force wordlists.",
  param_fuzz_query_hits: "Query parameter fuzz hits. We look for response changes that suggest hidden logic or unsafe parameter handling.",
  param_fuzz_body_hits: "Body parameter fuzz hits. We look for behavior deltas when adding/changing body fields.",
  param_fuzz_header_hits: "Header fuzz hits. We look for trust/misuse of attacker-controlled headers.",
  param_fuzz_cookie_hits: "Cookie fuzz hits. We look for state/control issues from manipulated cookie values.",
  injection_sqli_hits: "SQL Injection candidates. We inject SQL-like payloads and hunt for DB errors or response anomalies.",
  injection_nosqli_hits: "NoSQL Injection candidates. We inject operator-style payloads and watch for auth/query logic shifts.",
  injection_xpath_hits: "XPath Injection candidates. We test if XML/XPath queries can be altered by crafted input.",
  injection_ldap_hits: "LDAP Injection candidates. We test if LDAP filters are manipulable via user-controlled input.",
  server_input_os_command_hits: "OS Command Injection candidates. We test whether input reaches shell/system command execution.",
  server_input_path_traversal_hits: "Path Traversal candidates. We test if file path input can escape intended directories.",
  server_input_file_inclusion_hits: "File Inclusion candidates. We test for unsafe local/remote file loading behavior.",
  adv_injection_xxe_hits: "XXE candidates. We test XML parsing paths for external entity processing and file/SSRF access.",
  adv_injection_soap_hits: "SOAP injection candidates. We test SOAP/XML operations for unsafe parser/business logic handling.",
  adv_injection_ssrf_hits: "SSRF candidates. We test whether server-side requests can be redirected to attacker-chosen hosts.",
  adv_injection_smtp_hits: "SMTP injection candidates. We test mail-related fields for header/protocol injection patterns.",
  csrf_candidates: "State-changing endpoints that may require CSRF protection and were selected for replay checks.",
  csrf_findings: "CSRF risk findings. We look for cross-origin state changes accepted without robust anti-CSRF controls.",
  csrf_replay_log: "Request replay details for CSRF testing (baseline vs forged-origin/cookie replay behavior).",
  clickjacking_headers: "Observed frame-related headers/policies (X-Frame-Options and CSP frame-ancestors).",
  clickjacking_findings: "Potential clickjacking exposures where framing protections are weak/missing.",
  cors_replay_log: "CORS replay details using controlled Origin headers to validate trust policy behavior.",
  cors_findings: "Potential CORS misconfigurations (overly broad origin trust, credentials + weak origin validation).",
  open_redirect_candidates: "Endpoints that redirect and are suitable for open-redirect validation.",
  open_redirect_replay_log: "Replay details for redirect checks (baseline vs attacker-controlled destination behavior).",
  open_redirect_findings: "Potential open redirects where attacker-controlled redirect targets are accepted.",
  workflow_logic_candidates: "Multi-step flow endpoints selected for business-logic/state-machine consistency checks.",
  workflow_logic_findings: "Potential logic flaws from invalid step order, weak state validation, or replay inconsistencies.",
  workflow_logic_replay_log: "Replay traces for workflow/state tests across step transitions.",
  smuggling_stack_tool_runs: "Execution traces from smuggling/h2c/hop-by-hop/SSI-ESI tooling.",
  smuggling_stack_findings: "Potential request smuggling/stack parsing desync and related intermediary handling risks.",
  nmap_targets: "Hosts selected for Nmap service fingerprinting.",
  nmap_services: "Discovered open services/ports from Nmap; useful for exposed service triage.",
  nmap_searchsploit: "Searchsploit correlation output mapped from detected service fingerprints.",
  nuclei_findings: "Template-based vulnerability matches from nuclei (heuristic findings; manual verification required).",
  tier_isolation_ip_map: "Domain-to-IP mapping used to detect shared hosting and weak environment isolation.",
  tier_isolation_findings: "Potential segmentation/isolation issues where sensitive and public assets overlap on infra.",
  static_review_semgrep: "Raw Semgrep static-analysis output (source-level patterns that may indicate vulnerabilities).",
  static_review_gosec: "Raw Gosec static-analysis output for Go code security smells.",
  static_review_correlated: "Static findings correlated to discovered live endpoints for higher-priority review.",
  runops_scorecard_json: "Run completion scorecard in JSON format for pipeline health and stage coverage.",
  runops_scorecard_md: "Run completion scorecard in Markdown format for quick human review.",
  xss_reflected_hits: "Reflected XSS candidates where injected input appears in immediate responses in dangerous contexts.",
  xss_dom_hits: "DOM XSS candidates where client-side scripts may use untrusted data in unsafe sinks.",
  xss_stored_hits: "Stored XSS candidates where payloads may persist and execute for later viewers.",
  xss_scan_log: "Raw log output from Playwright-assisted XSS scan runs.",
};

export const LIST_FILES = [
  { type: "wildcards", label: "Wildcards", uploadable: true },
  { type: "domains", label: "All Domains", uploadable: true },
  { type: "domains_http", label: "HTTP Domains", uploadable: false },
  { type: "domains_dead", label: "Dead Domains", uploadable: false },
  { type: "apidomains", label: "All API Domains", uploadable: true },
  { type: "apidomains_http", label: "HTTP API Domains", uploadable: false },
  { type: "apidomains_dead", label: "Dead API Domains", uploadable: false },
  { type: "organizations", label: "Organizations", uploadable: true },
  { type: "ips", label: "IPs", uploadable: true },
  { type: "out_of_scope", label: "Out of scope", uploadable: true },
  { type: "robots_urls", label: "Robots URLs", uploadable: false },
  { type: "wayback_urls", label: "Wayback URLs", uploadable: false },
  { type: "katana_urls", label: "Katana URLs", uploadable: false },
  { type: "all_urls", label: "All URLs", uploadable: false },
  { type: "params_candidates", label: "Param Candidates", uploadable: false },
  { type: "param_fuzz_query_hits", label: "Param Fuzz Query Hits", uploadable: false },
  { type: "param_fuzz_body_hits", label: "Param Fuzz Body Hits", uploadable: false },
  { type: "param_fuzz_header_hits", label: "Param Fuzz Header Hits", uploadable: false },
  { type: "param_fuzz_cookie_hits", label: "Param Fuzz Cookie Hits", uploadable: false },
  { type: "injection_sqli_hits", label: "Injection SQLi Hits", uploadable: false },
  { type: "injection_nosqli_hits", label: "Injection NoSQLi Hits", uploadable: false },
  { type: "injection_xpath_hits", label: "Injection XPath Hits", uploadable: false },
  { type: "injection_ldap_hits", label: "Injection LDAP Hits", uploadable: false },
  { type: "server_input_os_command_hits", label: "Server Input OS Command Hits", uploadable: false },
  { type: "server_input_path_traversal_hits", label: "Server Input Path Traversal Hits", uploadable: false },
  { type: "server_input_file_inclusion_hits", label: "Server Input File Inclusion Hits", uploadable: false },
  { type: "adv_injection_xxe_hits", label: "Advanced Injection XXE Hits", uploadable: false },
  { type: "adv_injection_soap_hits", label: "Advanced Injection SOAP Hits", uploadable: false },
  { type: "adv_injection_ssrf_hits", label: "Advanced Injection SSRF Hits", uploadable: false },
  { type: "adv_injection_smtp_hits", label: "Advanced Injection SMTP Hits", uploadable: false },
  { type: "csrf_candidates", label: "CSRF Candidates", uploadable: false },
  { type: "csrf_findings", label: "CSRF Findings", uploadable: false },
  { type: "csrf_replay_log", label: "CSRF Replay Log", uploadable: false },
  { type: "clickjacking_headers", label: "Clickjacking Headers", uploadable: false },
  { type: "clickjacking_findings", label: "Clickjacking Findings", uploadable: false },
  { type: "cors_replay_log", label: "CORS Replay Log", uploadable: false },
  { type: "cors_findings", label: "CORS Findings", uploadable: false },
  { type: "open_redirect_candidates", label: "Open Redirect Candidates", uploadable: false },
  { type: "open_redirect_replay_log", label: "Open Redirect Replay Log", uploadable: false },
  { type: "open_redirect_findings", label: "Open Redirect Findings", uploadable: false },
  { type: "workflow_logic_candidates", label: "Workflow Logic Candidates", uploadable: false },
  { type: "workflow_logic_findings", label: "Workflow Logic Findings", uploadable: false },
  { type: "workflow_logic_replay_log", label: "Workflow Logic Replay Log", uploadable: false },
  { type: "smuggling_stack_tool_runs", label: "Smuggling Stack Tool Runs", uploadable: false },
  { type: "smuggling_stack_findings", label: "Smuggling Stack Findings", uploadable: false },
  { type: "nmap_targets", label: "Nmap Targets", uploadable: false },
  { type: "nmap_services", label: "Nmap Services", uploadable: false },
  { type: "nmap_searchsploit", label: "Nmap Searchsploit Correlation", uploadable: false },
  { type: "nuclei_findings", label: "Nuclei Findings", uploadable: false },
  { type: "tier_isolation_ip_map", label: "Tier Isolation IP Map", uploadable: false },
  { type: "tier_isolation_findings", label: "Tier Isolation Findings", uploadable: false },
  { type: "static_review_semgrep", label: "Static Review Semgrep", uploadable: false },
  { type: "static_review_gosec", label: "Static Review Gosec", uploadable: false },
  { type: "static_review_correlated", label: "Static Review Correlated", uploadable: false },
  { type: "runops_scorecard_json", label: "RunOps Scorecard JSON", uploadable: false },
  { type: "runops_scorecard_md", label: "RunOps Scorecard Markdown", uploadable: false },
  { type: "xss_reflected_hits", label: "XSS Reflected Hits", uploadable: false },
  { type: "xss_dom_hits", label: "XSS DOM Hits", uploadable: false },
  { type: "xss_stored_hits", label: "XSS Stored Hits", uploadable: false },
  { type: "xss_scan_log", label: "XSS Scan Log", uploadable: false },
  { type: "fuzzing_doc_hits", label: "Fuzzing Doc Hits", uploadable: false },
  { type: "fuzzing_dir_hits", label: "Fuzzing Dir Hits", uploadable: false },
];

export const GENERATED_FILE_GROUPS = [
  {
    title: "Mapping & Discovery",
    types: [
      "domains_http",
      "domains_dead",
      "apidomains_http",
      "apidomains_dead",
      "robots_urls",
      "wayback_urls",
      "katana_urls",
      "all_urls",
      "params_candidates",
    ],
  },
  {
    title: "Input & Injection Fuzzing",
    types: [
      "fuzzing_doc_hits",
      "fuzzing_dir_hits",
      "param_fuzz_query_hits",
      "param_fuzz_body_hits",
      "param_fuzz_header_hits",
      "param_fuzz_cookie_hits",
      "injection_sqli_hits",
      "injection_nosqli_hits",
      "injection_xpath_hits",
      "injection_ldap_hits",
      "server_input_os_command_hits",
      "server_input_path_traversal_hits",
      "server_input_file_inclusion_hits",
      "adv_injection_xxe_hits",
      "adv_injection_soap_hits",
      "adv_injection_ssrf_hits",
      "adv_injection_smtp_hits",
    ],
  },
  {
    title: "Client-Side Attack Classes",
    types: [
      "csrf_candidates",
      "csrf_findings",
      "csrf_replay_log",
      "clickjacking_headers",
      "clickjacking_findings",
      "cors_replay_log",
      "cors_findings",
      "open_redirect_candidates",
      "open_redirect_replay_log",
      "open_redirect_findings",
      "xss_reflected_hits",
      "xss_dom_hits",
      "xss_stored_hits",
      "xss_scan_log",
    ],
  },
  {
    title: "Logic, Architecture & Platform",
    types: [
      "workflow_logic_candidates",
      "workflow_logic_findings",
      "workflow_logic_replay_log",
      "smuggling_stack_tool_runs",
      "smuggling_stack_findings",
      "nmap_targets",
      "nmap_services",
      "nmap_searchsploit",
      "nuclei_findings",
      "tier_isolation_ip_map",
      "tier_isolation_findings",
    ],
  },
  {
    title: "Source Review & RunOps",
    types: [
      "static_review_semgrep",
      "static_review_gosec",
      "static_review_correlated",
      "runops_scorecard_json",
      "runops_scorecard_md",
    ],
  },
];
